# Generated by Django 4.2.4 on 2023-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='cafeteria.ItemPedido', to='cafeteria.producto'),
        ),
    ]
